// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovkmbpyakmkwgrzejyae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92a21icHlha21rd2dyemVqeWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTMzNDgsImV4cCI6MjA3MDc2OTM0OH0.g5g26D8sT-XjbFC4QyW5z93PRaDBLY4cjxUdaOJDybA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});