// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exwfohcfjxmouilxfqmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4d2ZvaGNmanhtb3VpbHhmcW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTQ5NjAsImV4cCI6MjA3MDc3MDk2MH0.wxUgqYdKtjOeurLOGZw3YqjCSPOEcP5FX4SnKp78CP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});